### ISSUE TITLE
_lazy_import preventing easy access to functions descriptions and arguments pre-filling

### ISSUE THREAD

**Issue by Maxtimer97** [NeuroBench/neurobench#61]
https://github.com/NeuroBench/neurobench/blob/b2adcf91c4725b411c2dc631a38cb7009fa8f903/neurobench/utils.py#L3-L5

I have the impression the use of _lazy_import is limiting the features (on VSCode in my case) to visualize functions descriptions and pre-filling features. 
Is it indeed the case and then can we find a better solution?

**Comment by ben9809** [comment]
The module's loading is postponed until the method or class it offers is actually used in the code by using _lazy_import. Due to this delayed loading, the contents of the module are not accessible during the static analysis stage, which takes place when the IDE examines the script prior to it being executed. Because this module hasn't been loaded and examined yet, the IDE is unable to offer features like autocomplete, syntax highlighting, or inline documentation for its components.

**Comment by jasonlyik** [comment]
Since we have the documentation/examples up now, I think it we don't have to worry about this
